### ISSUE TITLE
Nicknames should be per-room

### ISSUE THREAD

**Issue by nathyong** [nathyong/web500#10]
Currently the implementation uses 'usernames' which persist forever on database, but the database should probably be replaced with something more ephemeral for now, and usernames should be able to be reused, at least for a small scale, and for a non-competitive game like 500.

**Comment by nathyong** [comment]
This involves getting rid of the database for usernames, too, and the room structure will need to be moved around a little bit but that's not too much of an issue. If we make it login-less (since there is no longer much point in keeping the session alive for longer than the lifetime of a room) then this makes #4 redundant also.

**Comment by vinceau** [comment]
#4 was supposed to give players who disconnect/accidentally close their tab/window, have their browser crash, a second chance at continuing the game. If we remove #4, what's the correct way to handle player disconnection? Just force restart a new game?

**Comment by nathyong** [comment]
We can use session specific cookies instead of secret keys, eliminating the need for users to keep track of keys for each game. We can rely on cookies for all users who will play..
